prometheus:
  crdApiGroup: "monitoring.coreos.com"

serviceMonitor:
  enabled: true
  processExporter:
    enabled: true
    ### interval for scrape
    #interval: "10s"
    jobLabel: "process-exporter"
    metricRelabelings: []
    relabelings: []

  grafana:
    enabled: true
    ### interval for scrape
    #interval: "10s"
    jobLabel: "grafana"
    metricRelabelings: []
    relabelings: []

grafanaDashboard:
  enable: true
  # namespace installed grafana
  namespace: fed
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
      label: grafana_datasource
      prometheusAddress: "lma-prometheus-fed-master-prometheus:9090" 
