{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.additionalScrapeConfigs }}
{{- range $key, $val := .Values.serviceMonitor.additionalScrapeConfigs }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $val.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $val.name }}
spec:
  endpoints:
  - interval: {{ default "30s" $val.interval }}
    port: metrics
    path: {{ default "/metrics" $val.path }}
{{- if $val.basicAuth }}
    basicAuth:
      password:
        key: {{ $val.basicAuth.password.key }}
        name: {{ $val.basicAuth.password.name }}
      username:
        key: {{ $val.basicAuth.username.key }}
        name: {{ $val.basicAuth.username.name }}
{{- end }}
{{- if $val.params }}
    params:
{{ toYaml $val.params | indent 6 }}
{{- end }}
{{- if $val.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml $val.metricRelabelings | indent 6) . }}
{{- end }}
{{- if $val.relabelings }}
    relabelings:
{{ toYaml $val.relabelings | indent 6 }}
{{- end }}
  jobLabel: {{ $val.name }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app: {{ $val.name }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ $val.name }}
  labels:
    app: {{ $val.name }}
  namespace: {{ $.Release.Namespace }}
subsets:
  - addresses:
    - ip: {{ $val.address }}
    ports:
    - name: metrics
      port: {{ default 30008 $val.port }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $val.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $val.name }}
spec:
  ports:
  - name: metrics 
    port: {{ default 30008 $val.port }}
    protocol: TCP
    targetPort: {{ default 30008 $val.port }}
---
{{- end }}
{{- end }}
