{{- if .Values.metricbeat.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
spec:
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
      serviceAccountName: metricbeat
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        resources:
{{- if .Values.metricbeat.resources }}
{{ toYaml .Values.metricbeat.resources | indent 10 }}
{{ else }}
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
{{- end }}
        image: {{ .Values.metricbeat.image }}
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOSTS
          value: {{ .Values.metricbeat.elasticsearch.host }}
        - name: KIBANA_HOST
          value: {{ .Values.metricbeat.kibana.host }}
        - name: ELASTICSEARCH_USERNAME
          value: {{ .Values.metricbeat.elasticsearch.username }}
        - name: ELASTICSEARCH_PASSWORD
          value: {{ .Values.metricbeat.elasticsearch.password }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: metricbeat-config
      - name: modules
        configMap:
          defaultMode: 0600
          name: metricbeat-modules
{{- end }}
