{{- if and .Values.tacoWatcher.joinCluster.enabled .Values.tacoWatcher.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.tacoWatcher.rbac.name }}-cr
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.tacoWatcher.rbac.name }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.tacoWatcher.rbac.name }}-cr
subjects:
- kind: ServiceAccount
  name: {{ .Values.tacoWatcher.rbac.name }}-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tacoWatcher.rbac.name }}-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tacoWatcher.rbac.name }}-manual-token
  namespace: {{ .Release.Namespace }}
  annotations: 
    "helm.sh/hook-delete-policy": before-hook-creation 
    kubernetes.io/service-account.name: {{ .Values.tacoWatcher.rbac.name }}-sa
type: kubernetes.io/service-account-token
{{- end }}
